services:
  Evrinoma\PackingListBundle\Fetch\Handler\BaseGetHandler:
    tags:
      - { name: 'evrinoma.fetch.handler' }

  Evrinoma\PackingListBundle\Fetch\Handler\BasePostHandler:
    tags:
      - { name: 'evrinoma.fetch.handler' }