imports:
  - { resource: services/packing_list.yml }
  - { resource: services/group.yml }
  - { resource: services/list_item.yml }
  - { resource: services/depart.yml }
  - { resource: services/logistics.yml }
  - { resource: services/logistics_group.yml }
  - { resource: services/packing_list_group.yml }
