imports:
  - { resource: services/packing_list.yml }
  - { resource: services/list_item.yml }
  - { resource: services/depart.yml }
  - { resource: services/logistics.yml }

services:
  Evrinoma\UtilsBundle\Persistence\ManagerRegistry:
    alias: evrinoma.packing_list.persistence

  evrinoma.packing_list.persistence:
    class: Evrinoma\UtilsBundle\Persistence\ManagerRegistry
    arguments:
      - '@evrinoma.fetch.manager.fetch'

  Evrinoma\PackingListBundle\Fetch\Description\ListItem\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\Depart\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\PackingList\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\ListItem\GetDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\PackingList\GetDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Handler\BaseHandler:
    tags:
      - { name: 'evrinoma.fetch.handler' }