imports:
  - { resource: tests/depart.yml }
  - { resource: tests/list_item.yml }
  - { resource: tests/logistics.yml }
  - { resource: tests/packing_list.yml }
  - { resource: tests/packing_list_group.yml }
  - { resource: tests/group.yml }
