services:
  Evrinoma\PackingListBundle\Fetch\Description\ListItem\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\Depart\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\PackingList\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\ListItem\GetDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Description\PackingList\GetDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  Evrinoma\PackingListBundle\Fetch\Handler\BaseHandler:
    tags:
      - { name: 'evrinoma.fetch.handler' }
