services:
  Evrinoma\PackingListBundle\Fetch\Description\Logistics\PostDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  evrinoma.packing_list.logistics.fetch.post:
    alias: Evrinoma\PackingListBundle\Fetch\Description\Logistics\PostDescription
    public: true