services:
  Evrinoma\PackingListBundle\Fetch\Description\Logistics\PutDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  evrinoma.packing_list.logistics.fetch.put:
    alias: Evrinoma\PackingListBundle\Fetch\Description\Logistics\PutDescription
    public: true