services:
  Evrinoma\PackingListBundle\Fetch\Description\PackingList\CriteriaDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  evrinoma.packing_list.packing_list.fetch.criteria:
    alias: Evrinoma\PackingListBundle\Fetch\Description\PackingList\CriteriaDescription

  Evrinoma\PackingListBundle\Fetch\Description\PackingList\GetDescription:
    tags:
      - { name: 'evrinoma.fetch.description' }

  evrinoma.packing_list.packing_list.fetch.get:
    alias: Evrinoma\PackingListBundle\Fetch\Description\PackingList\GetDescription
